language: "en" # Supported languages -> hu, de, en, es

database:
  type: "sqlite" # Supported types -> mysql, sqlite
  mysql:
    host: localhost
    port: 3306
    database: coma112
    username: root
    password: ""
    # You shouldn't touch this part except if you are familiar with it.
    ssl: false
    certificateverification: false
    poolsize: 10
    lifetime: 1800000

# This is the suggestion item in the GUI.
suggestion-item:
  material: PAPER
  name: "&c{player}'s suggestion &8(&7#{id}&8)"
  custommodeldata: 0
  lore:
    - ""
    - "&cSUGGESTION: &4{suggestion}"
    - ""
filler-glass-item:
  material: GRAY_STAINED_GLASS_PANE
  name: " "
  custommodeldata: 0
  lore: []

# Menu Configuration
menu:
  back-item:
    amount: 1
    material: RED_STAINED_GLASS
    name: "&cBack"
    custommodeldata: 0
    slot: 45
  forward-item:
    amount: 1
    material: GREEN_STAINED_GLASS
    name: "&aForward"
    custommodeldata: 0
    slot: 53
  title: "&cSUGGESTIONS"
  size: 54
  update-tick: 2
  filler-glass: true

forward-on-click: true # You can set that if you click on a suggestion then it should be forwarded to Discord.

# Webhook
# webhook.enabled -> You can enable and disable the webhook feature
# webhook.url -> Discord Webhook URL

webhook:
  suggestion-created-embed:
    enabled: true
    url: "https://discord.com/api/webhooks/1270362542782550077/ICs4lfSa2YbjUfnflrO0VhMS6zI5u9xiKU9bvdwGWcz_3d6bk9tYrTq6v9MGfO6BHVYq"
    title: "SUGGESTION CREATED"
    description: "**{player}** created a suggestion: **{suggestion}**"
    color: "RED"
    author-name: ""
    author-url: ""
    author-icon: ""
    footer-text: "SENT BY CSUGGESTION"
    footer-icon: ""
    thumbnail: ""
    image: ""
  suggestion-forwarded-embed:
    url: "https://discord.com/api/webhooks/1270363789639946343/eR8uEler_th5FsP6-KtVLAzZEjVWMAIotX-_LPEgKvdGxh1BgkJLEW7QjJcRrh5Gp4_9"
    title: "SUGGESTION FORWARDED"
    description: "**{player}** created a suggestion: **{suggestion}**"
    color: "RED"
    author-name: ""
    author-url: ""
    author-icon: ""
    footer-text: "SENT BY CSUGGESTION"
    footer-icon: ""
    thumbnail: ""
    image: ""
